name: doxygen
on: [push, workflow_dispatch]
jobs:
  doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: apt-get install doxygen
      - run: cd ./doc/doxygen/ | exec doxygen
